modLoader = "javafml"
loaderVersion = "[47,)"
license = "Custom"

[[mods]]
modId = "wildernature"
version = "${version}"
displayName = "[Let's Do] Wilder Nature"
authors = "satisfy, jason13"
description = '''
Discover enchanting new animals like playful squirrels and majestic deers! Visit the bounty board for fun challenges and fabulous rewards.
'''
logoFile = "pack.png"

[[dependencies.wildernature]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wildernature]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wildernature]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wildernature]]
modId = "curios"
mandatory = true
versionRange = "[5.10.0,)"
ordering = "AFTER"
side = "BOTH"
